title = "example"
addr = "127.0.0.1:54321"
data_dir = "/tmp"
instance_count = 1

[instance_info]
	[instance_info.server]
	count=1

[[test_cmd]]
cmd = "start"
instances = ["server1"]
dir = "/tmp"
args = "./server"
#probe function url
probe = "http://127.0.0.1:8080/probefunc"
