addr = "127.0.0.1:54321"
data_dir = "/tmp"
instance_count = 1

[instance]
	[instance.server]
	count=1

[[test_cmd]]
cmd = "start"
instances = ["server1"]
dir = "/tmp"
args = "nohup ./test &"
#probe function url
probe = "http://127.0.0.1:8080/probe/server/start"

[[test_cmd]]
cmd = "dropport"
instances = ["server1"]
args = "54300"
probe = "http://127.0.0.1:8080/probe/server/dropport"

[[test_cmd]]
cmd = "recoverport"
instances = ["server1"]
args = "54300"
probe = "http://127.0.0.1:8080/probe/server/recoverport"

[[test_cmd]]
cmd = "pause"
instances = ["server1"]
probe = "http://127.0.0.1:8080/probe/server/pause"

[[test_cmd]]
cmd = "continue"
instances = ["server1"]
probe = "http://127.0.0.1:8080/probe/server/continue"

[[test_cmd]]
cmd = "restart"
instances = ["server1"]
args = "nohup ./test &"
probe = "http://127.0.0.1:8080/probe/server/restart"

[[test_cmd]]
cmd = "stop"
instances = ["server1"]
probe = "http://127.0.0.1:8080/probe/server/stop"

[[test_cmd]]
cmd = "shutdown"
instances = ["server1"]
