title = "example"

[baseAttr]
intanceCount = 13

[instanceInfo]
	[intance.server]
	count = 6
	[instance.proxy]
	count = 3
	[instance.zk]
	count=3

[[testCmd]]
cmd = "start"
instances = [server1, server2, server3, server4, server5, server6]
dir = "/tmp"
args = "./server"
probe = "probe function name"

[[testCmd]]
cmd = "start"
instances = [proxy1, proxy2, proxy3]
dir = "/tmp"
args = "./proxy"
probe = "probe function name"
